--	Crear una consulta SELECT que genere las 20 secciones con mas venta en moneda local
SELECT
    COD_SECC AS "SECCIÓN",
    CONCAT('S/.', TO_CHAR(VAL_MONT_SOLI_TOTAL_SECC)) AS "TOTAL DE VENTAS FACTURADAS POR SECCIÓN",
    VAL_UNID_TOTAL_SECC AS "UNIDADES VENDIDAS DE DIFERENTES MARCAS POR SECCIÓN"
FROM 
(
    SELECT
        COD_SECC,
        SUM(TO_NUMBER(REPLACE(VAL_MONT_SOLI, '.', ','))) AS "VAL_MONT_SOLI_TOTAL_SECC",
        SUM(VAL_UNID_LBEL) + SUM(VAL_UNID_CYZO) + SUM(VAL_UNID_ESIK) AS "VAL_UNID_TOTAL_SECC"
    FROM PEDIDOS  
    WHERE VAL_ESTA_PEDI = 'FACTURADO'
    GROUP BY COD_SECC
    ORDER BY 2 DESC
)
FETCH FIRST 20 ROWS ONLY;
