--Crear una consulta SELECT que genere la venta por ZONA en unidades y moneda local
SELECT 
    COD_ZONA AS "ZONA",
    CONCAT('S/.', TO_CHAR(SUM(TO_NUMBER(REPLACE(VAL_MONT_SOLI, '.', ','))))) AS "TOTAL DE VENTAS FACTURADAS POR ZONA",
    SUM(VAL_UNID_LBEL) + SUM(VAL_UNID_CYZO) + SUM(VAL_UNID_ESIK) AS "UNIDADES VENDIDAS DE DIFERENTES MARCAS POR ZONA"
FROM PEDIDOS 
WHERE VAL_ESTA_PEDI = 'FACTURADO'
GROUP BY COD_ZONA
ORDER BY COD_ZONA ASC
